services:
  pg_database:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - "./data/postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:${POSTGRES_PORT}"

