services:
  pg-database:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data:rw
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - pg-network

  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
    - ./data/pgadmin_data:/var/lib/pgadmin
    depends_on:
      - pg-database
    networks:
      - pg-network

  data-ingestion:
    build:
      dockerfile: week1-data-ingestion-pipeline/Dockerfile
    networks:
      - pg-network
    depends_on:
      - pg-database
    command: ["--csv_path", "green_tripdata_2019-01.csv.gz", "--host", "pg-database"]

networks:
  pg-network:

